default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kickme_development

test:
  <<: *default
  database: kickme_test

production:
  <<: *default
  database: kickme_production
